// <auto-generated />
using System;
using BigliettApp.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BigliettApp.DataLayer.Migrations
{
    [DbContext(typeof(BiglietteriaDbContext))]
    partial class BiglietteriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BigliettApp.DataLayer.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cognome");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("BigliettApp.DataLayer.Models.Prenotazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dataPrenotazione");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<int>("IdSpettacolo")
                        .HasColumnType("int")
                        .HasColumnName("idSpettacolo");

                    b.Property<string>("Posto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Posto");

                    b.Property<decimal>("PrezzoFinale")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("prezzo");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdSpettacolo");

                    b.ToTable("prenotazione");
                });

            modelBuilder.Entity("BigliettApp.DataLayer.Models.Spettacolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dataOra");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descrizione");

                    b.Property<int>("Durata")
                        .HasColumnType("int")
                        .HasColumnName("durata");

                    b.Property<decimal>("PrezzoBase")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("prezzo");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("titolo");

                    b.HasKey("Id");

                    b.ToTable("spettacolo");
                });

            modelBuilder.Entity("BigliettApp.DataLayer.Models.Prenotazione", b =>
                {
                    b.HasOne("BigliettApp.DataLayer.Models.Cliente", "FkClienteNavigation")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BigliettApp.DataLayer.Models.Spettacolo", "FkSpettacoloNavigation")
                        .WithMany()
                        .HasForeignKey("IdSpettacolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FkClienteNavigation");

                    b.Navigation("FkSpettacoloNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
